### ISSUE TITLE
Prevent action from deleting package with "latest" version

### ISSUE THREAD

**Issue by msalzburg** [navikt/remove-package-versions#3]
Hey @christeredvartsen we are happily using your action for several repos/packages. Thank you so much!

Since we started to generate multiple packages, e.g. "package-abc" and "package-abc-stage", from a single repository, e.g. "package-abc", we experience a somewhat strange deletion behaviour. The action would never delete the "package-abc:latest" package, but will always delete the "package-abc-stage:latest" package. It appears like the action processes the package differently if the package name does not equal the repository name. 

Since we like to keep our "latest" packages we crafted a quick fix (PR incoming),
maybe you want to straighten things up or want to provide another option ;)

**Comment by christeredvartsen** [comment]
Thanks for the feedback on this, and sorry to hear that you have experienced some unwanted behaviour. A pull request to fix this is very welcome! ❤️

**Comment by msalzburg** [comment]
No worries ;) As mentioned the PR fixed everything for us - you might want to handle things differently and/or add an option for it ...

**Comment by msalzburg** [comment]
Since most users of this github action are hooked to the main branch via

`navikt/remove-package-versions@main` 

and now "profit" from the introduced "keep latest" behaviour it would make sense to enable a potential input/option by default ...
